app:
  name: focus-app
  version: v1
replicaCount: 1

image:
  repository: ${{ env.REGISTRY }}/$IMAGE_NAME
  tag:
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: 
     kubernetes.io/ingress.class: nginx
     kubernetes.io/tls-acme: "true"
  paths: "/"
  hosts:
    - host: chart-example.local
  tls: []


resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
